//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace sql.builder.Properties {
//    using System;
    
    
//    /// <summary>
//    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
//    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    internal class Resources {
        
//        private static global::System.Resources.ResourceManager resourceMan;
        
//        private static global::System.Globalization.CultureInfo resourceCulture;
        
//        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
//        internal Resources() {
//        }
        
//        /// <summary>
//        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Resources.ResourceManager ResourceManager {
//            get {
//                if (object.ReferenceEquals(resourceMan, null)) {
//                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sql.builder.Properties.Resources", typeof(Resources).Assembly);
//                    resourceMan = temp;
//                }
//                return resourceMan;
//            }
//        }
        
//        /// <summary>
//        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
//        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Globalization.CultureInfo Culture {
//            get {
//                return resourceCulture;
//            }
//            set {
//                resourceCulture = value;
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap AddChildItem_24 {
//            get {
//                object obj = ResourceManager.GetObject("AddChildItem_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap AddItem_24 {
//            get {
//                object obj = ResourceManager.GetObject("AddItem_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Byte[].
//        /// </summary>
//        internal static byte[] base_xlsx {
//            get {
//                object obj = ResourceManager.GetObject("base_xlsx", resourceCulture);
//                return ((byte[])(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
//        /// </summary>
//        internal static System.Drawing.Icon cell_edit {
//            get {
//                object obj = ResourceManager.GetObject("cell_edit", resourceCulture);
//                return ((System.Drawing.Icon)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
//        /// </summary>
//        internal static System.Drawing.Icon check {
//            get {
//                object obj = ResourceManager.GetObject("check", resourceCulture);
//                return ((System.Drawing.Icon)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap Commit_24 {
//            get {
//                object obj = ResourceManager.GetObject("Commit_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap CommitAndClose_24 {
//            get {
//                object obj = ResourceManager.GetObject("CommitAndClose_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
//        /// </summary>
//        internal static System.Drawing.Icon copy {
//            get {
//                object obj = ResourceManager.GetObject("copy", resourceCulture);
//                return ((System.Drawing.Icon)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap copy_16 {
//            get {
//                object obj = ResourceManager.GetObject("copy_16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
//        /// </summary>
//        internal static System.Drawing.Icon delete {
//            get {
//                object obj = ResourceManager.GetObject("delete", resourceCulture);
//                return ((System.Drawing.Icon)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap delete_16x16 {
//            get {
//                object obj = ResourceManager.GetObject("delete_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap DeleteItem_24 {
//            get {
//                object obj = ResourceManager.GetObject("DeleteItem_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap ExportXls_16 {
//            get {
//                object obj = ResourceManager.GetObject("ExportXls_16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap ExportXls_161 {
//            get {
//                object obj = ResourceManager.GetObject("ExportXls_161", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Byte[].
//        /// </summary>
//        internal static byte[] formats {
//            get {
//                object obj = ResourceManager.GetObject("formats", resourceCulture);
//                return ((byte[])(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap GridChoiceRow {
//            get {
//                object obj = ResourceManager.GetObject("GridChoiceRow", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap GridExportToFile_24 {
//            get {
//                object obj = ResourceManager.GetObject("GridExportToFile_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap GridRowAdd_24 {
//            get {
//                object obj = ResourceManager.GetObject("GridRowAdd_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap GridRowDelete_24 {
//            get {
//                object obj = ResourceManager.GetObject("GridRowDelete_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap info_16x16 {
//            get {
//                object obj = ResourceManager.GetObject("info_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
//        /// </summary>
//        internal static System.Drawing.Icon infoenergo_inverted {
//            get {
//                object obj = ResourceManager.GetObject("infoenergo_inverted", resourceCulture);
//                return ((System.Drawing.Icon)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
//        /// </summary>
//        internal static System.Drawing.Icon move {
//            get {
//                object obj = ResourceManager.GetObject("move", resourceCulture);
//                return ((System.Drawing.Icon)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap Ok_16 {
//            get {
//                object obj = ResourceManager.GetObject("Ok_16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap Ok_24 {
//            get {
//                object obj = ResourceManager.GetObject("Ok_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap Paste_16 {
//            get {
//                object obj = ResourceManager.GetObject("Paste_16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap Refresh_24 {
//            get {
//                object obj = ResourceManager.GetObject("Refresh_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap Settings_24 {
//            get {
//                object obj = ResourceManager.GetObject("Settings_24", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }
//    }
//}
