//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace sql.builder.Properties {
    
    
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
//    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
//        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
//        public static Settings Default {
//            get {
//                return defaultInstance;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("")]
//        public string skinName {
//            get {
//                return ((string)(this["skinName"]));
//            }
//            set {
//                this["skinName"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("")]
//        public string workFolder {
//            get {
//                return ((string)(this["workFolder"]));
//            }
//            set {
//                this["workFolder"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("ur_mat")]
//        public string testQueryS1 {
//            get {
//                return ((string)(this["testQueryS1"]));
//            }
//            set {
//                this["testQueryS1"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("")]
//        public string testQueryS2 {
//            get {
//                return ((string)(this["testQueryS2"]));
//            }
//            set {
//                this["testQueryS2"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("")]
//        public string testQueryS3 {
//            get {
//                return ((string)(this["testQueryS3"]));
//            }
//            set {
//                this["testQueryS3"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("True")]
//        public bool oldCompile {
//            get {
//                return ((bool)(this["oldCompile"]));
//            }
//            set {
//                this["oldCompile"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("True")]
//        public bool UpdateSettings {
//            get {
//                return ((bool)(this["UpdateSettings"]));
//            }
//            set {
//                this["UpdateSettings"] = value;
//            }
//        }
//    }
//}
