  CREATE MATERIALIZED VIEW "ASUSE"."VV_DAY" ("DAT_DAY")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ASUSE_TBL" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select  (ADD_MONTHS(trunc(SYSDATE,'YEAR'), -12*15) + level - 1) as dat_day from dual
      connect by level <= ADD_MONTHS(trunc(SYSDATE,'YEAR'), 12*10) - ADD_MONTHS(trunc(SYSDATE,'YEAR'), -12*15)