-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2026 Gilles DAROLD. All rights reserved.
-- DATASOURCE: 

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

select 'm' as val;
