CREATE USER qlikview
IDENTIFIED BY qlikview1
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
/
GRANT SELECT ANY TABLE TO qlikview
/
GRANT CONNECT TO qlikview
/
ALTER USER qlikview DEFAULT ROLE ALL
/

