CREATE TABLE VR_LAYOUT_SETTINGS
(
    kod_ls           NUMBER NOT NULL PRIMARY KEY,
    -- пользователь
    puser            VARCHAR2(30) NOT NULL,
    -- имя настройки отображения
    name             VARCHAR2(300) NOT NULL,
    -- xml-файл с настройкой
    data             NCLOB,
    d_m              DATE NOT NULL,
    u_m              VARCHAR2(30) NOT NULL
)
/
-- сиквенс
CREATE SEQUENCE SQ_LAYOUT_SETTINGS
START WITH 1
INCREMENT BY 1;
/    
-- тригер
CREATE OR REPLACE TRIGGER T_VR_LAYOUT_SETTINGS
BEFORE INSERT OR UPDATE
ON VR_LAYOUT_SETTINGS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        SELECT SQ_LAYOUT_SETTINGS.NEXTVAL INTO :NEW.KOD_LS FROM DUAL;
    END IF;
    SELECT SYSDATE,USER INTO :NEW.D_M,:NEW.U_M FROM DUAL;
END;
/
-- constraint на каскадное удаление
ALTER TABLE VR_LAYOUT_SETTINGS ADD CONSTRAINT KS_USER_VR_LAYOUT_SETTINGS FOREIGN KEY (PUSER) REFERENCES KS_USER (PUSER) ON DELETE CASCADE
/
-- public синоним
CREATE OR REPLACE PUBLIC SYNONYM VR_LAYOUT_SETTINGS FOR VR_LAYOUT_SETTINGS
/
-- Grants for Table
GRANT DELETE ON VR_LAYOUT_SETTINGS TO public
/
GRANT INSERT ON VR_LAYOUT_SETTINGS TO public
/
GRANT SELECT ON VR_LAYOUT_SETTINGS TO public
/
GRANT UPDATE ON VR_LAYOUT_SETTINGS TO public
/

COMMENT ON TABLE VR_LAYOUT_SETTINGS IS 'Таблица для хранения настроек визуального отображения форм проекта Sql.Builder в формате xml'
/
COMMENT ON COLUMN VR_LAYOUT_SETTINGS.KOD_LS IS 'ключ'
/
COMMENT ON COLUMN VR_LAYOUT_SETTINGS.PUSER IS 'пользователь'
/
COMMENT ON COLUMN VR_LAYOUT_SETTINGS.NAME IS 'имя настройки'
/
COMMENT ON COLUMN VR_LAYOUT_SETTINGS.DATA IS 'xml-файл с настройкамой отображения'
/
COMMENT ON COLUMN VR_LAYOUT_SETTINGS.D_M IS 'дата последнего редактирования'
/
COMMENT ON COLUMN VR_LAYOUT_SETTINGS.U_M IS 'последний редактирующий пользователь'
/

