-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2026 Gilles DAROLD. All rights reserved.
-- DATASOURCE: 
set client_encoding to 'UTF8';

\
set ON_ERROR_STOP on
set check_function_bodies = false;

create
or REPLACE view asuse.nv_account_sost_nal (
  kod_account_sost,
  kod_account_priem,
  tip_tarif_sost,
  cust,
  price,
  kod_account,
  kod_nal,
  kod_naltax,
  pr_add,
  tax,
  nal,
  nachisl
) as
select a .KOD_ACCOUNT_SOST,
  a .KOD_ACCOUNT_PRIEM,
  a .TIP_TARIF_SOST,
  a .CUST,
  a .PRICE,
  a .KOD_ACCOUNT,
  n.kod_nal,
  n.kod_naltax,
  n.pr_add,
  n.tax,
  a .cust * a .price * n.drob nal,
  case
    when n.pr_add = 1 then a .cust * a .price + a .cust * a .price * n.drob
    else a .cust * a .price
  end as nachisl
from (
    select b.kod_account,
      n.pr_add,
      n.kod_nal,
      n.tax,
      n.kod_naltax,
      coalesce(sum(n.nal), 0) nal,
      case
        when b.nachisl - coalesce(sum(nal), 0) = 0 then 0
        else coalesce(sum(n.nal), 0) /(nachisl - coalesce(sum(nal), 0))
      end drob
    from ec_account.nr_account b
      left outer join ec_account.nr_account_nal n on (b.kod_account = n.kod_account)
    group by b.kod_account,
      n.pr_add,
      n.kod_nal,
      n.tax,
      n.kod_naltax,
      b.nachisl
  ) n,
  ec_calc.nr_account_sost a
where n.kod_account = a .kod_account;