-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2026 Gilles DAROLD. All rights reserved.
-- DATASOURCE: 

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE OR REPLACE VIEW asuse.nv_account (kod_account, kod_f46, kod_numobj, kod_dog, kod_bu, kod_numobj_sa, ym, den, num_priem, dat_priem, rym, dat_promezhut, tarif, kod_f23, voltage, vid_t, num_t, cust, price, nachisl, info, vist_day, kod_vid_act, kod_sf, pr_sf, u_m, d_m, pr_hand, raschet, kod_bu_akt, nal, nds, nach, money, vid_real, kod_ist, kodp, dep, podr, kod_dog_fin, ndog, prn_elved, prizn_selo, vid_avans, kod_tar_free, kod_dhh, kodinterval, edizm, tep_el, gr_point, vid_t_name, kod_osn_pererasch, kod_tarif_rate, kod_plan, kod_account_parent, pr_gener, kod_av, kod_reglament, cust_rg) AS SELECT
   A.KOD_ACCOUNT , A.KOD_F46 , A.KOD_NUMOBJ , A.KOD_DOG, A.kod_bu
 , A.KOD_NUMOBJ_SA , A.YM , A.DEN, A.NUM_PRIEM , A.DAT_PRIEM , A.RYM, A.DAT_PROMEZHUT
 , A.TARIF , A.KOD_F23 , A.VOLTAGE , A.VID_T , S.NUM_T, A.CUST
 , A.PRICE , A.NACHISL , A.INFO , A.VIST_DAY , A.kod_vid_act, A.kod_sf, A.pr_sf, A.U_M , A.D_M
 , A.PR_HAND , A.raschet, A.kod_bu_akt
 , SUM(B.NAL) AS NAL ,  SUM(CASE WHEN B.KOD_NAL=1 THEN  B.NAL  ELSE 0 END ) AS NDS, A.NACHISL-coalesce(SUM(B.NAL),0) AS NACH
 , coalesce(A.NACHISL-coalesce(SUM(case B.pr_add when 1 then B.NAL else 0 end),0), round((A.CUST*A.PRICE)::numeric, 2)) AS MONEY
 , S.VID_REAL, D.kod_ist, D.kodp, D.dep, D.podr, D.kod_dog_fin, D.ndog, D.prn_elved, T.prizn_selo, A.vid_avans, A.kod_tar_free, A.kod_dhh, A.kodinterval
 , S.edizm
 , case when D.tep_el=-8 then D.tep_el else S.tep_el end tep_el
 , O.GR_POINT, S.name as vid_t_name, A.KOD_OSN_PERERASCH, A.kod_tarif_rate, A.kod_plan, A.kod_account_parent, A.pr_gener
 , A.KOD_AV, A.KOD_REGLAMENT, A.cust_rg
FROM fin_doc.sk_nachisl s, dog.kr_dogovor d, ec_account.nr_account a
LEFT OUTER JOIN ec_account.nr_account_nal b ON (A.KOD_ACCOUNT = B.KOD_ACCOUNT)
LEFT OUTER JOIN tarif.ks_tarif t ON (A.tarif = T.tarif)
LEFT OUTER JOIN dog_object.kr_numobj o ON (A.kod_numobj = O.kod_numobj)
WHERE A.VID_T = S.VID_T AND D.kod_dog = A.kod_dog   group by A.KOD_ACCOUNT , A.KOD_F46 , A.KOD_NUMOBJ , A.KOD_DOG, A.kod_bu
 , A.KOD_NUMOBJ_SA , A.YM , A.DEN, A.NUM_PRIEM , A.DAT_PRIEM , A.RYM, A.DAT_PROMEZHUT
 , A.TARIF , A.KOD_F23 , A.VOLTAGE , A.VID_T , S.NUM_T, A.CUST
 , A.PRICE , A.NACHISL , A.INFO , A.VIST_DAY , A.kod_vid_act, A.kod_sf, A.pr_sf, A.U_M , A.D_M
 , A.PR_HAND, A.raschet, A.kod_bu_akt, S.VID_REAL, D.kod_ist, D.kodp, D.dep, D.podr, D.kod_dog_fin, D.ndog, D.prn_elved
 , T.prizn_selo, A.vid_avans, A.kod_tar_free, A.kod_dhh, A.kodinterval
 , S.edizm, D.tep_el, S.tep_el, O.GR_POINT, S.name, A.KOD_OSN_PERERASCH, A.kod_tarif_rate, A.kod_plan, A.kod_account_parent, A.pr_gener
 , A.kod_av, A.KOD_REGLAMENT, A.cust_rg;


